namespace PseudoDataGen;

using System.Globalization;
using System.Text;

using LibGit2Sharp;

public static class Program
{
    private const string RepositoryPath = @"C:\Users\machi\Desktop\Works\Git\docker-gitlab";
    private const int MaxCommits = 500;

    public static int Main(string[] args)
    {
        if (args.Length < 1)
        {
            Console.Error.WriteLine("Usage: PseudoDataGen <output-cs-path>");
            return 1;
        }

        var outputPath = args[0];

        using var repo = new Repository(RepositoryPath);

        var roots = new List<object>();
        foreach (var branch in repo.Branches)
        {
            if (branch.Tip is not null)
            {
                roots.Add(branch.Tip);
            }
        }
        foreach (var tag in repo.Tags)
        {
            var c = tag.Target.Peel<Commit>();
            if (c is not null)
            {
                roots.Add(c);
            }
        }
        if (repo.Head.Tip is not null)
        {
            roots.Add(repo.Head.Tip);
        }

        var filter = new CommitFilter
        {
            SortBy = CommitSortStrategies.Topological | CommitSortStrategies.Time,
            IncludeReachableFrom = roots,
        };
        var commits = repo.Commits.QueryBy(filter).Take(MaxCommits).ToList();

        var includedShas = new HashSet<string>(commits.Select(c => c.Sha), StringComparer.Ordinal);

        var refList = new List<(string Sha, string Name, string Kind)>();
        if (repo.Head.Tip is not null && includedShas.Contains(repo.Head.Tip.Sha))
        {
            refList.Add((repo.Head.Tip.Sha, "HEAD", "Head"));
        }
        foreach (var branch in repo.Branches)
        {
            if (branch.Tip is null)
            {
                continue;
            }
            if (!includedShas.Contains(branch.Tip.Sha))
            {
                continue;
            }
            refList.Add((branch.Tip.Sha, branch.FriendlyName, branch.IsRemote ? "RemoteBranch" : "LocalBranch"));
        }
        foreach (var tag in repo.Tags)
        {
            var c = tag.Target.Peel<Commit>();
            if (c is null)
            {
                continue;
            }
            if (!includedShas.Contains(c.Sha))
            {
                continue;
            }
            refList.Add((c.Sha, tag.FriendlyName, "Tag"));
        }

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("namespace WorkSkiaGitMaui.Data;");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Globalization;");
        sb.AppendLine();
        sb.AppendLine("public static class PseudoRepository");
        sb.AppendLine("{");
        sb.AppendLine("    public static readonly IReadOnlyList<PseudoCommit> Commits = new PseudoCommit[]");
        sb.AppendLine("    {");
        foreach (var c in commits)
        {
            var parentShas = c.Parents.Select(p => Quote(p.Sha));
            var parentArr = string.Join(", ", parentShas);
            sb.Append("        new PseudoCommit { ");
            sb.Append($"Sha = {Quote(c.Sha)}, ");
            sb.Append($"Author = {Quote(c.Author.Name)}, ");
            sb.Append($"AuthorWhen = DateTimeOffset.Parse({Quote(c.Author.When.ToString("O", CultureInfo.InvariantCulture))}, CultureInfo.InvariantCulture), ");
            sb.Append($"Summary = {Quote(c.MessageShort)}, ");
            sb.Append($"ParentShas = new string[] {{ {parentArr} }} ");
            sb.AppendLine("},");
        }
        sb.AppendLine("    };");
        sb.AppendLine();
        sb.AppendLine("    public static readonly IReadOnlyList<PseudoRef> Refs = new PseudoRef[]");
        sb.AppendLine("    {");
        foreach (var r in refList)
        {
            sb.Append("        new PseudoRef { ");
            sb.Append($"TargetSha = {Quote(r.Sha)}, ");
            sb.Append($"Name = {Quote(r.Name)}, ");
            sb.Append($"Kind = {Quote(r.Kind)} ");
            sb.AppendLine("},");
        }
        sb.AppendLine("    };");
        sb.AppendLine("}");

        Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
        File.WriteAllText(outputPath, sb.ToString());
        Console.WriteLine($"Wrote {commits.Count} commits and {refList.Count} refs to {outputPath}");
        return 0;
    }

    private static string Quote(string s)
    {
        var encoded = s
            .Replace("\\", "\\\\", StringComparison.Ordinal)
            .Replace("\"", "\\\"", StringComparison.Ordinal)
            .Replace("\r", "\\r", StringComparison.Ordinal)
            .Replace("\n", "\\n", StringComparison.Ordinal)
            .Replace("\t", "\\t", StringComparison.Ordinal);
        return "\"" + encoded + "\"";
    }
}
