using System.CommandLine;
using System.CommandLine.Parsing;
using Microsoft.Extensions.DependencyInjection;
using WorkCliHost.Core;

namespace WorkCliHost.Samples;

/// <summary>
/// Example: Using a custom action builder for AOT-friendly command construction.
/// This demonstrates how to provide custom command building logic.
/// In the future, this will be auto-generated by Source Generator.
/// </summary>
public static class AotFriendlyExample
{
    public static async Task<int> RunWithCustomBuilderAsync(string[] args)
    {
        var builder = CliHost.CreateBuilder(args);

        builder.ConfigureCommands(commands =>
        {
            // カスタムアクションビルダーを使用してコマンドを登録
            // 将来的にはSource Generatorがこの部分を自動生成
            commands.AddCommand<SimpleCalculatorCommand>(
                actionBuilder: CreateSimpleCalculatorActionBuilder()
            );
            
            // リフレクションベース（通常の方法）
            commands.AddCommand<MessageCommand>();
        });

        var host = builder.Build();
        return await host.RunAsync();
    }

    // カスタムアクションビルダー: AOTフレンドリーなコマンド構築
    // 将来的にはSource Generatorが自動生成する
    private static CommandActionBuilder CreateSimpleCalculatorActionBuilder()
    {
        return context =>
        {
            // 1. 引数を作成
            var arg1 = new Argument<int>("a")
            {
                Description = "First number"
            };
            var arg2 = new Argument<int>("b")
            {
                Description = "Second number"
            };
            var operation = new Argument<string>("operation")
            {
                Description = "Operation (+, -, *, /)",
                DefaultValueFactory = _ => "+"
            };

            var arguments = new Argument[] { arg1, arg2, operation };

            // 2. コアアクションを作成
            // インスタンス、CommandContext、FilterPipelineは呼び出し側で処理
            CommandActionDelegate coreAction = async (instance, parseResult, commandContext) =>
            {
                // インスタンスは既に生成済み（呼び出し側が生成）
                var command = (SimpleCalculatorCommand)instance;

                // 引数値を設定
                command.A = parseResult.GetValue(arg1);
                command.B = parseResult.GetValue(arg2);
                command.Operation = parseResult.GetValue(operation)!;

                // コマンド実行
                await instance.ExecuteAsync(commandContext);
            };

            // 3. 引数リストとコアアクションを返す
            return (arguments, coreAction);
        };
    }
}

// カスタムビルダーで使用するコマンド
[CliCommand("calc", Description = "Simple calculator")]
public sealed class SimpleCalculatorCommand : ICommandDefinition
{
    // Source Generatorがこの属性を読み取る
    [CliArgument<int>("a", Description = "First number")]
    public int A { get; set; }

    [CliArgument<int>("b", Description = "Second number")]
    public int B { get; set; }

    [CliArgument<string>("operation", Description = "Operation (+, -, *, /)", DefaultValue = "+")]
    public string Operation { get; set; } = "+";

    public ValueTask ExecuteAsync(CommandContext context)
    {
        var result = Operation switch
        {
            "+" => A + B,
            "-" => A - B,
            "*" => A * B,
            "/" => A / B,
            _ => throw new ArgumentException($"Unknown operation: {Operation}")
        };

        Console.WriteLine($"{A} {Operation} {B} = {result}");
        return ValueTask.CompletedTask;
    }
}
