using System.CommandLine;
using Microsoft.Extensions.DependencyInjection;
using WorkCliHost.Core;

namespace WorkCliHost.Samples;

/// <summary>
/// Example: Using a custom command builder for AOT-friendly command construction.
/// This demonstrates how to provide custom command building logic.
/// In the future, this will be auto-generated by Source Generator.
/// </summary>
public static class AotFriendlyExample
{
    public static async Task<int> RunWithCustomBuilderAsync(string[] args)
    {
        var builder = CliHost.CreateBuilder(args);

        builder.ConfigureCommands(commands =>
        {
            // カスタムビルダーを使用してコマンドを登録
            // 将来的にはSource Generatorがこの部分を自動生成
            commands.AddCommand<SimpleCalculatorCommand>(
                builder: CreateSimpleCalculatorCommandBuilder()
            );
            
            // リフレクションベース（通常の方法）
            commands.AddCommand<MessageCommand>();
        });

        var host = builder.Build();
        return await host.RunAsync();
    }

    // カスタムビルダー: リフレクションを使わずにコマンドを構築
    // 将来的にはSource Generatorが自動生成する
    private static CommandBuilder CreateSimpleCalculatorCommandBuilder()
    {
        return (commandType, serviceProvider) =>
        {
            // コマンド情報（Source Generatorが取得）
            var command = new Command("calc", "Simple calculator");

            // 引数を手動で追加（Source Generatorが生成）
            var arg1 = new Argument<int>("a")
            {
                Description = "First number"
            };
            var arg2 = new Argument<int>("b")
            {
                Description = "Second number"
            };
            var operation = new Argument<string>("operation")
            {
                Description = "Operation (+, -, *, /)",
                DefaultValueFactory = _ => "+"
            };

            command.Arguments.Add(arg1);
            command.Arguments.Add(arg2);
            command.Arguments.Add(operation);

            // アクションを設定（Source Generatorが生成）
            command.SetAction(async parseResult =>
            {
                // DIからコマンドインスタンスを取得
                var instance = (SimpleCalculatorCommand)ActivatorUtilities
                    .CreateInstance(serviceProvider, commandType);

                // 引数を手動で設定（Source Generatorが生成）
                instance.A = parseResult.GetValue(arg1);
                instance.B = parseResult.GetValue(arg2);
                instance.Operation = parseResult.GetValue(operation)!;

                // フィルタパイプラインを通して実行
                var filterPipeline = serviceProvider.GetRequiredService<FilterPipeline>();
                
                return await filterPipeline.ExecuteAsync(commandType, instance, CancellationToken.None);
            });

            return command;
        };
    }
}

// カスタムビルダーで使用するコマンド
[CliCommand("calc", Description = "Simple calculator")]
public sealed class SimpleCalculatorCommand : ICommandDefinition
{
    // Source Generatorがこの属性を読み取る
    [CliArgument<int>("a", Description = "First number")]
    public int A { get; set; }

    [CliArgument<int>("b", Description = "Second number")]
    public int B { get; set; }

    [CliArgument<string>("operation", Description = "Operation (+, -, *, /)", DefaultValue = "+")]
    public string Operation { get; set; } = "+";

    public ValueTask ExecuteAsync(CommandContext context)
    {
        var result = Operation switch
        {
            "+" => A + B,
            "-" => A - B,
            "*" => A * B,
            "/" => A / B,
            _ => throw new ArgumentException($"Unknown operation: {Operation}")
        };

        Console.WriteLine($"{A} {Operation} {B} = {result}");
        return ValueTask.CompletedTask;
    }
}
